opt_in_rules: 
  - empty_count
  - first_where

included:
  - Sources

excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true