opt_in_rules: 
  - empty_count
  - first_where

included:
  - Sources

disabled_rules:
  - trailing_whitespace

excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level:
    warning: 3
    error: 4
  function_level:
    warning: 5
    error: 7