//
//  ThreeDSAuthRequestParameters.swift
//  MercadoPagoSDK
//
//  Created by Guilherme Prata Costa on 26/08/25.
//

/// Authentication request parameters required for 3D Secure server communication.
///
/// This structure contains all the necessary parameters generated by the 3DS SDK
/// that must be sent to your backend for 3D Secure server authentication.
/// Your backend will use these parameters to communicate with the 3DS server
/// and determine if a challenge is required.
///
/// ## Integration Flow
///
/// 1. Obtain these parameters from ``MPThreeDS/requestParameterspaymentMethodId:)``
/// 2. Send all parameters to your backend API
/// 3. Your backend forwards them to the 3DS server for authentication
/// 4. Based on the server response, either complete the flow or start a challenge
///
/// ## Example
/// ```swift
/// let authData = try threeDS.requestParameters(paymentMethodId: "visa")
/// let params = authData.parameters
///
/// // Send to your backend
/// sendToBackend([
///     "sdkAppId": params.sdkAppId,
///     "deviceData": params.deviceData,
///     "sdkEphemeralPublicKey": params.sdkEphemeralPublicKey,
///     "sdkReferenceNumber": params.sdkReferenceNumber,
///     "sdkTransactionId": params.sdkTransactionId
/// ])
/// ```
public struct MPThreeDSAuthRequestParameters: Sendable {
    /// SDK App ID that identifies the 3DS SDK.
    public let sdkAppId: String
    
    /// Encrypted device information collected by the 3DS SDK.
    public let deviceData: String
    
    /// SDK ephemeral public key for secure communication.
    public let sdkEphemeralPublicKey: String
    
    /// Unique reference number for this SDK instance.
    public let sdkReferenceNumber: String
    
    /// Unique transaction ID generated by the SDK.
    public let sdkTransactionId: String
}
