default_platform(:ios)

platform :ios do
  desc "Execute Tests"
  lane :test do
    scan(
      scheme: "MercadoPagoSDK-iOS",
      package_path: ".",
      destination: "platform=iOS Simulator,name=iPhone 16",
      result_bundle: true,
      code_coverage: true,
      output_directory: "fastlane/test_output",
      buildlog_path: "fastlane/test_output"
    )

    xcov(
      is_swift_package: true,
      output_directory: "fastlane/xcov_output",
      minimum_coverage_percentage: 80.0
    )
  end
end